/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xuankemis;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class CourseAddInterFrm extends javax.swing.JFrame {
ControlObject co=new ControlObject();
FormObject fo=new FormObject();
    /**
     * Creates new form CourseAddInterFrm
     */
    public CourseAddInterFrm() throws Exception {
        initComponents();
	int windowWidth = this.getWidth(); //获得窗口宽
        int windowHeight = this.getHeight(); //获得窗口高
        Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包
        Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸
        int screenWidth = screenSize.width; //获取屏幕的宽
        int screenHeight = screenSize.height; //获取屏幕的高
        this.setLocation(screenWidth / 2 - 550 / 2, screenHeight / 2 - 250 / 2);
        this.setExtendedState(JFrame.NORMAL);
        this.setSize(550,250);
        this.setTitle("添加课程");
        allteachers();
        this.jComboBox1.setSelectedItem(null);
        this.jComboBox2.setSelectedItem(null);
        this.TeacherNameTxt.setText("");
    }

    private void allteachers() throws Exception{
    DataBase database=new DataBase();
    jComboBox1.removeAllItems();
    Connection con=null; 
    con=database.getCon();
    ResultSet rs=co.QueryList(con, "tinfo", "tno", "");
    
    while (rs.next()) {
    jComboBox1.addItem(rs.getString("Tno"));
    }
   database.closeCon(con);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        courseNameTxt = new javax.swing.JTextField();
        capacityTxt = new javax.swing.JTextField();
        jb_add = new javax.swing.JButton();
        jb_reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TeacherNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CourseIdTxt = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();

        jLabel3.setText("任课老师");

        jLabel4.setText("课程容量");

        jb_add.setText("添加");
        jb_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_addActionPerformed(evt);
            }
        });

        jb_reset.setText("重置");
        jb_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_resetActionPerformed(evt);
            }
        });

        jLabel1.setText("课程名称");

        jLabel2.setText("上课时间");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("课程编号");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_add, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(39, 39, 39)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CourseIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(courseNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(capacityTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TeacherNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jb_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CourseIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(capacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_add)
                    .addComponent(jb_reset))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_resetActionPerformed
        // TODO add your handling code here:
    this.resetValue();   
    }//GEN-LAST:event_jb_resetActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    try {
        // TODO add your handling code here:
        DataBase database=new DataBase();
        String tno=this.jComboBox1.getSelectedItem().toString();
        Connection con=database.getCon();
        ResultSet rs=co.QueryList(con, "tinfo", "tno", tno);
        while (rs.next()) {
            this.TeacherNameTxt.setText(rs.getString("tname"));
        }
        database.closeCon(con);
    } catch (SQLException ex) {
        Logger.getLogger(CourseAddInterFrm.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(CourseAddInterFrm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jb_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_addActionPerformed
    
    try {
        DataBase database=new DataBase();
        int n=0;
        String courseId=this.CourseIdTxt.getText();
        String courseName=this.courseNameTxt.getText();
        String courseTime=this.jComboBox2.getSelectedItem().toString();
        String TeacherId = this.jComboBox1.getSelectedItem().toString();
        Integer capacity=Integer.parseInt(this.capacityTxt.getText());
        Integer selectedStudents=0;
      
        Course course=new Course();
        
        course.setcourseID(courseId);
        course.setcourseName(courseName);
        course.SetTeacherID(TeacherId);
        course.setcourseTime(courseTime);
        course.SetmaxStudents(capacity);
        course.SetSelectedStudents(selectedStudents);
      
        if(StringUtil.isEmpty(courseId)){
            fo.ShowInfo(this, "课程编号不能为空!");
            return;
        }        
        if(StringUtil.isEmpty(courseName)){
            fo.ShowInfo(this, "课程名称不能为空!");
            return;
        }
        if(StringUtil.isEmpty(courseTime)){
            fo.ShowInfo(this, "上课时间不能为空!");
            return;
        }
        if(StringUtil.isEmpty(jComboBox1.getSelectedItem().toString())){
            fo.ShowInfo(this, "教师不能为空!");
            return;
        }
        if(StringUtil.isEmpty(capacity.toString())){
            fo.ShowInfo(this, "课程容量不能为空!");
            return;
        }
        
        Connection con=null;
        con=database.getCon();
        
        if (co.CanAdd(con,"t_course","courseId",courseId)){        
            n = co.AddCourse(con,course);
            if(n==1){
				fo.ShowInfo(this, "添加成功!");
				this.resetValue();
			}else{
				fo.ShowInfo(this, "添加失败!");
			}
            
            
        }
        else
        {
            fo.ShowInfo(this, "课程编号重复!");
        }
    } catch (Exception ex) {
        Logger.getLogger(CourseAddInterFrm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jb_addActionPerformed
private void resetValue(){
    this.CourseIdTxt.setText("");
    this.courseNameTxt.setText("");
    this.jComboBox2.setSelectedItem(null);
    this.capacityTxt.setText("");
    this.TeacherNameTxt.setText("");
    this.jComboBox1.setSelectedItem(null);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseAddInterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseAddInterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseAddInterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseAddInterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CourseAddInterFrm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CourseAddInterFrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseIdTxt;
    private javax.swing.JTextField TeacherNameTxt;
    private javax.swing.JTextField capacityTxt;
    private javax.swing.JTextField courseNameTxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jb_add;
    private javax.swing.JButton jb_reset;
    // End of variables declaration//GEN-END:variables
}
