/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xuankemis;
import java.awt.Font;
import java.sql.Connection;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import xuankemis.ControlObject;
import xuankemis.StringUtil;
import xuankemis.FormObject;
/**
 *
 * @author Administrator
 */
public class LogOnFrm extends javax.swing.JFrame {
    DataBase database=new DataBase();
    ControlObject co=new ControlObject();
    FormObject fo=new FormObject();
    public static Student currentStudent;
    public static Administrator currentAdmin;
    
    /**
     * Creates new form LogOnFrm
     */
    public LogOnFrm() {
        Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
//get(Object key)或get(Object key, Locale l)，返回Object，从默认值中返回一个对象。参数： key - 指定所需对象的 Object，l - 需要该对象的 Locale。
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
//put(Object key, Object value)，返回Object，在开发人员默认值中存储一个对象。此方法是 getDefaults().put(key, value) 的一个覆盖方法。此方法仅对开发人员默认值有效，对系统默认值和外观默认值无效。 简单地说就是把一个组件抽出来设置它的一些属性，比如设置全局组件的字体：
			}
		}
        initComponents();
        this.setTitle("登录");
        this.setLocationRelativeTo(null);
	this.jrb_student.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jrb_student = new javax.swing.JRadioButton();
        jrb_admin = new javax.swing.JRadioButton();
        jb_logOn = new javax.swing.JButton();
        jb_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("隶书", 1, 24)); // NOI18N
        jLabel1.setText("学生选课系统");

        jLabel2.setText("账号");

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("密码");

        jrb_student.setText("学生");
        jrb_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_studentActionPerformed(evt);
            }
        });

        jrb_admin.setText("管理员");
        jrb_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_adminActionPerformed(evt);
            }
        });

        jb_logOn.setText("登录");
        jb_logOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logOnActionPerformed(evt);
            }
        });

        jb_reset.setText("重置");
        jb_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(userNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(passwordTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jb_logOn)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jrb_student, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jb_reset)))))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_student)
                    .addComponent(jrb_admin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_logOn)
                    .addComponent(jb_reset))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_logOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logOnActionPerformed
        // TODO add your handling code here:
            String userName = userNameTxt.getText();
	    String password = new String(passwordTxt.getPassword());
		if (StringUtil.isEmpty(userName)) {
			fo.ShowInfo(this, "用户名不能为空!");
			return;
		}
		if (StringUtil.isEmpty(password)) {
			fo.ShowInfo(this, "密码不能为空!");
			return;
		}
		Connection con=null;
		if (this.jrb_student.isSelected()) {
			Student student = new Student();
                        student.setStudentID(userName);
                        student.setSpassword(password);
                       
			try {
				con=database.getCon();  
                               
				currentStudent = co.VerifyStudent(con,student);
				if (currentStudent != null) {
					this.dispose();
					new MainFrm_student().setVisible(true);
				} else {
					JOptionPane.showMessageDialog(this, "登录失败!");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "登录失败!");
			}finally{
				try {
					database.closeCon(con);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		} else if (this.jrb_admin.isSelected()) {
			Administrator admin = new Administrator();
                        admin.setAdministratorID(userName);
                        admin.setAdpassword(password);
			try {
				con=database.getCon();
				currentAdmin = co.VerifyAdministrator(con, admin);
				if (currentAdmin != null) {
					this.dispose();
					new MainFrm_admin().setVisible(true);
				} else {
					JOptionPane.showMessageDialog(this, "登录失败!");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "登录失败!");
			}finally{
				try {
					database.closeCon(con);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}     
        
        
    }//GEN-LAST:event_jb_logOnActionPerformed

    private void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_resetActionPerformed
        // TODO add your handling code here:
        this.resetValue();
    }//GEN-LAST:event_jb_resetActionPerformed

    private void jrb_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_studentActionPerformed
        // TODO add your handling code here:
        if (jrb_student.isSelected()){
            jrb_admin.setSelected(false);
        }
    }//GEN-LAST:event_jrb_studentActionPerformed

    private void jrb_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_adminActionPerformed
        // TODO add your handling code here:
        if (jrb_admin.isSelected()){
            jrb_student.setSelected(false);
        }
    }//GEN-LAST:event_jrb_adminActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed
    private void resetValue() {
		this.userNameTxt.setText("");
		this.passwordTxt.setText("");
		this.jrb_student.setSelected(true);
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOnFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOnFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOnFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOnFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogOnFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_logOn;
    private javax.swing.JButton jb_reset;
    private javax.swing.JRadioButton jrb_admin;
    private javax.swing.JRadioButton jrb_student;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JFormattedTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
