/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xuankemis;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class MainFrm_admin extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm_admin
     */
    
    public MainFrm_admin() {
        initComponents();
        int windowWidth = this.getWidth(); //获得窗口宽
        int windowHeight = this.getHeight(); //获得窗口高
        Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包
        Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸
        int screenWidth = screenSize.width; //获取屏幕的宽
        int screenHeight = screenSize.height; //获取屏幕的高
        //this.setLocation(screenWidth / 2 - windowWidth / 2, screenHeight / 2 - windowHeight / 2);//设置窗口居中显示
        this.setLocation(screenWidth / 2 - 700 / 2, screenHeight / 2 - 500 / 2);
        this.setExtendedState(JFrame.NORMAL);
        this.setSize(700,500);
        this.setTitle("选课管理信息系统");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        newuser = new javax.swing.JMenuItem();
        modifyuser = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiCourseAdd = new javax.swing.JMenuItem();
        jmiCourseManage = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiStudentView = new javax.swing.JMenuItem();
        jmiStudentPassword = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiCourseView = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setName(""); // NOI18N
        table.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(table);
        table.setBounds(0, 0, 720, 520);

        jMenu1.setText("基本操作");

        jMenu5.setText("用户管理");

        newuser.setText("新增用户");
        newuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuserActionPerformed(evt);
            }
        });
        jMenu5.add(newuser);

        modifyuser.setText("用户管理");
        modifyuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyuserActionPerformed(evt);
            }
        });
        jMenu5.add(modifyuser);

        jMenu1.add(jMenu5);

        jMenu6.setText("课程信息管理");

        jmiCourseAdd.setText("增加课程条目");
        jmiCourseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCourseAddActionPerformed(evt);
            }
        });
        jMenu6.add(jmiCourseAdd);

        jmiCourseManage.setText("管理课程信息");
        jmiCourseManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCourseManageActionPerformed(evt);
            }
        });
        jMenu6.add(jmiCourseManage);

        jMenu1.add(jMenu6);

        jMenu4.setText("学生信息管理");

        jmiStudentView.setText("查看学生资料");
        jmiStudentView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStudentViewActionPerformed(evt);
            }
        });
        jMenu4.add(jmiStudentView);

        jmiStudentPassword.setText("管理学生密码");
        jmiStudentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStudentPasswordActionPerformed(evt);
            }
        });
        jMenu4.add(jmiStudentPassword);

        jMenu1.add(jMenu4);

        jMenu3.setText("选课信息管理");

        jmiCourseView.setText("查看选课情况");
        jmiCourseView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCourseViewActionPerformed(evt);
            }
        });
        jMenu3.add(jmiCourseView);

        jMenu1.add(jMenu3);

        jmiExit.setText("退出系统");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("帮助");

        jMenuItem1.setText("操作指南");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("联系技术人员");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuserActionPerformed
        UserAddInterFrm userFrm = new UserAddInterFrm();
        userFrm.setVisible(true);
        this.table.add(userFrm);
    }//GEN-LAST:event_newuserActionPerformed

    private void modifyuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyuserActionPerformed
        UserManageInterFrm umf = null ;
        try {
            umf = new UserManageInterFrm();
        } catch (Exception ex) {
            Logger.getLogger(MainFrm_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        umf.setVisible(true);
        this.table.add(umf);
    }//GEN-LAST:event_modifyuserActionPerformed

    private void jmiCourseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCourseAddActionPerformed
        // TODO add your handling code here:
        CourseAddInterFrm courseAddInterFrm = null;
        try {
            courseAddInterFrm = new CourseAddInterFrm();
        } catch (Exception ex) {
            Logger.getLogger(MainFrm_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
	courseAddInterFrm.setVisible(true);
	this.table.add(courseAddInterFrm);
    }//GEN-LAST:event_jmiCourseAddActionPerformed

    private void jmiCourseManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCourseManageActionPerformed
        try {
            // TODO add your handling code here:
            CourseManageInterFrm courseManageInterFrm = new CourseManageInterFrm();
            courseManageInterFrm.setVisible(true);
            this.table.add(courseManageInterFrm);
        } catch (Exception ex) {
            Logger.getLogger(MainFrm_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiCourseManageActionPerformed

    private void jmiStudentViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStudentViewActionPerformed
        // TODO add your handling code here:
        StudentViewInterFrm studentViewInterFrm = new StudentViewInterFrm();
	studentViewInterFrm.setVisible(true);
	this.table.add(studentViewInterFrm);
    }//GEN-LAST:event_jmiStudentViewActionPerformed

    private void jmiStudentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStudentPasswordActionPerformed
        // TODO add your handling code here:
        StudentPasswordInterFrm studentPasswordInterFrm = new StudentPasswordInterFrm();
	studentPasswordInterFrm.setVisible(true);
	this.table.add(studentPasswordInterFrm);
    }//GEN-LAST:event_jmiStudentPasswordActionPerformed

    private void jmiCourseViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCourseViewActionPerformed
        // TODO add your handling code here:
        CourseViewInterFrm courseViewInterFrm = new CourseViewInterFrm();
	courseViewInterFrm.setVisible(true);
	this.table.add(courseViewInterFrm);
    }//GEN-LAST:event_jmiCourseViewActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "确定要退出系统吗？");
		if (result == 0) {
			this.dispose();
		}
    }//GEN-LAST:event_jmiExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmiCourseAdd;
    private javax.swing.JMenuItem jmiCourseManage;
    private javax.swing.JMenuItem jmiCourseView;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiStudentPassword;
    private javax.swing.JMenuItem jmiStudentView;
    private javax.swing.JMenuItem modifyuser;
    private javax.swing.JMenuItem newuser;
    private javax.swing.JDesktopPane table;
    // End of variables declaration//GEN-END:variables
}
